### ISSUE TITLE
What about releasing another (stable) version?

### ISSUE THREAD

**Issue by rugk** [singpolyma/openpgp-php#10]
Could you try to make the library a bit stable and release another version?

Or do you want to wait until your PR's in the [upstream repo](https://github.com/bendiken/openpgp-php) are merged, so that the new version will be released there?

**Comment by singpolyma** [comment]
Release where?  It's release right here for now :)

**Comment by rugk** [comment]
There: https://github.com/singpolyma/openpgp-php/releases

Currently the only release is five years old.

Alternatively you could of course also make a stable branch or something like this where you only push the changes from the master branch if you think they are stable enough to be used productive.

**Comment by singpolyma** [comment]
Oh, that's just a git tag. Upstream made that, possibly before I even got involved.  I hadn't noticed it was there, to be honest.

**Comment by rugk** [comment]
So yes, I could change the title of this issue: Please provide git tags. :smile:

**Comment by singpolyma** [comment]
What benefit would that serve in this case?  Just curious.

**Comment by rugk** [comment]
The benefit of release tags is that you - at first have version numbers, so you can [semantically versionize](http://semver.org/) the libary - and you can make stable versions so projects which depend on your library don't have to use a (potentially) unstable version, but can use the latest release. And if you use semantically versioning they also know if the underlying library (yours) changes so that the know if their implementation breaks and they have to adjust it.
That's just a small summary... :smiley: 

More information:
* https://help.github.com/articles/about-releases/

And you can get the download count: https://help.github.com/articles/getting-the-download-count-for-your-releases/ :wink:

**Comment by singpolyma** [comment]
Sure, I know why one might make a release of a software product generally.  I guess in this case it would require me to make a decision about how stable the API is, etc.  Like, I could tag whatever is at HEAD right now and call it 0.2.0 -- I guess there could be an advantage, but it seems pretty arbitrary here.

**Comment by rugk** [comment]
> I guess in this case it would require me to make a decision about how stable the API is
Yes of course. 
> I could tag whatever is at HEAD right now and call it 0.2.0
Well, yes. If you think it's stable.
But at some point you have to add a release. At least it would be very useful: Even if it's only that you can have points of the software which need to name a commit hash. :smiley:

**Comment by singpolyma** [comment]
Alright, I've tagged 0.2.0 from HEAD to give us a starting point.

**Comment by rugk** [comment]
Nice. :+1: 
So you manage it now in this fork. So I consider https://github.com/bendiken/openpgp-php outdated.
And we finally have a up-to-date release here (which is not 5 years old :smiley:).

**Comment by rugk** [comment]
BTW you also have to update this here: https://github.com/singpolyma/openpgp-php/blob/master/lib/openpgp.php#L8
