### ISSUE TITLE
How to verify document with detached signature?

### ISSUE THREAD

**Issue by henry-h** [singpolyma/openpgp-php#100]
How to verify document with detached signature?

**Comment by singpolyma** [comment]
You should be able to unarmour and then parse the detached signature file to get the SignaturePacket.  Then construct a LiteralDataPacket containing the data from the file.  Finally make an OpenPGP_Message with the SignaturePacket first followed by the LiteralDataPacket. Now you should be able to treat this message as an *attached* signature and verify as per the example.
