### ISSUE TITLE
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.

### ISSUE THREAD

**Issue by jamieduk** [singpolyma/openpgp-php#101]
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.

**Comment by peter279k** [comment]
Please look at these [comments](https://github.com/laravel/ui/issues/134#issuecomment-676385024).

I think it's about the warning message for `phpunit/phpunit` and just ignore them.

**Comment by roisuladib** [comment]
ho to overcome "Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested"
