### ISSUE TITLE
Bootstrap test?

### ISSUE THREAD

**Issue by rugk** [singpolyma/openpgp-php#11]
I doubt that [this test] (https://github.com/singpolyma/openpgp-php/blob/master/tests/bootstrap.php#L2) will work. There is just no vendor dir nor a autoload.php file in this repo somewhere.

Anyway maybe I'm mistaken - I haven't tested this.

**Comment by vstm** [comment]
Thank you for your question - sorry for my late answer (haven't subscribed to these issues here).

The bootstrap.php is not an actual test-file. It doesn't contain any test-cases so it's not listed in the `phpunit.xml` as a test-file.

It's only of use if you are using composer for dependency management. Composer will create the `vendor/autoload.php`, and if you run `phpunit` it will include that file and make use of the Composer autoloader. 

Of course it doesn't require you to use composer. You can still install the required libraries with the correct version by hand. In that case the `phpunit`-command still runs without problems, the `@`-sign tells `include_once` to silently ignore the missing file and not display any warnings or erros messages.

I hope I could clear things up - just ask if you have any further questions about that.

**Comment by rugk** [comment]
Okay, thanks for the explanation.
