### ISSUE TITLE
New tagged release version

### ISSUE THREAD

**Issue by urashimakeitaro** [singpolyma/openpgp-php#111]
Hello,
I apologize if this is the wrong place to ask for that but there's been a lot of commits since the last release (v 0.3.0) in April 2017. Are there any plans to release the library as-is for a new release version? 

I'm just asking because a developer who uses your library for one of his WordPress plugins told me in reply to a question I asked him, that because there's no tagged release upstream with the codebase (as-is at the moment), he can’t easily reference that specific commit history version from Composer.

Thanks for reading and please keep that great project running!

**Comment by singpolyma** [comment]
The latest tag and release is actually 0.4.0 from August 2019.  Now, there has still been work since then so I'll look at cutting a new release soon.

**Comment by singpolyma** [comment]
Ok, everything seemed fine so I've also made a 0.5.0 release now.

**Comment by urashimakeitaro** [comment]
> 
> 
> Ok, everything seemed fine so I've also made a 0.5.0 release now.

I'd really like to thank you so much for your fast reply and release of the new version!
