### ISSUE TITLE
Support for phpseclib3 

### ISSUE THREAD

**Issue by allan-simon** [singpolyma/openpgp-php#116]
We're currently using phpseclib 3 in our project and unfortunately openpgp-php only support version 2

would you be interested in a PR that bring this compatibility ?

**Comment by singpolyma** [comment]
For sure, that could be useful

**Comment by allan-simon** [comment]
ok I will submit tomorrow a  draft PR,  I still have some test failing for which I may require your insight

**Comment by meglio** [comment]
So where is the PR after 6 months? :)

**Comment by singpolyma** [comment]
this is done now
