### ISSUE TITLE
Bump version to php 7.3?

### ISSUE THREAD

**Issue by Rotzbua** [singpolyma/openpgp-php#117]
`"phpunit/phpunit": "^9.0"` requires `php>=7.3` so php versions below can not be tested properly. Php versions below are EOL anyway. Sodium is also not available.
But composer still allows this old php versions. Shouldn't they be dropped?

If somebody wants to install the latest release anyway, it can be forced by composer with ` --ignore-platform-reqs` or sticking to an old release.

**Comment by singpolyma** [comment]
`sodium` is optional (only gets used if you require that file) just like `phpseclib` is optional (but used so commonly in practise that it ended up listed as a requirement), but you're right that even CI doesn't run on anything less than 7.3 anymore so maybe we should drop the older versions.
