### ISSUE TITLE
OpenPGP_PublicSubkeyPacket in SubKey exemple?

### ISSUE THREAD

**Issue by puggan** [singpolyma/openpgp-php#131]
In the subkey exemple:
https://github.com/singpolyma/openpgp-php/blob/1c3bdcd2d9c6113c2d6b768e208e7432a48d3a1e/examples/keygenSubkeys.php#L61

Guess this should be OpenPGP_PublicSubkeyPacket ?

(If I was more sure I would do a PR, but just started playing around whit this library today)

**Comment by jstanden** [comment]
The keygen example creates a private (secret) key with a separate sub-key for encryption. The referenced line with the modulus, exponents, and primes is definitely a secret key.

The public key is derived from the secret key at the end of the example.
