### ISSUE TITLE
Deprecated dynamic property usage in PHP 8.2+

### ISSUE THREAD

**Issue by jstanden** [singpolyma/openpgp-php#138]
When using the library in PHP 8.2+ with deprecation warnings being logged, we get the following entries:

* Creation of dynamic property OpenPGP_PublicSubkeyPacket::$input is deprecated in singpolyma/openpgp-php/lib/openpgp.php line 464

* Creation of dynamic property OpenPGP_PublicSubkeyPacket::$length is deprecated singpolyma/openpgp-php/lib/openpgp.php line 465

* Creation of dynamic property OpenPGP_SignaturePacket_EmbeddedSignaturePacket::$input is deprecated in singpolyma/openpgp-php/lib/openpgp.php line 880

* Creation of dynamic property OpenPGP_SignaturePacket_SignatureCreationTimePacket::$length is deprecated in singpolyma/openpgp-php/lib/openpgp.php line 881

* Creation of dynamic property OpenPGP_SignaturePacket_KeyFlagsPacket::$flags is deprecated in singpolyma/openpgp-php/lib/openpgp.php line 1204

A quick workaround is adding those properties to the `OpenPGP_Packet` base class (line 425):

```php
class OpenPGP_Packet {
  public $data, $flags, $input, $length, $size, $tag;
```

**Comment by jstanden** [comment]
It looks like this was fixed in commit https://github.com/singpolyma/openpgp-php/commit/f4dbc2f370b3d4eaa7e0cf8307b670606038e62e

But it's not in the 0.6.0 version from Composer.

**Comment by singpolyma** [comment]
If you test my changes for `hash_head` now in master as well, I'll do a 0.7 tag after that

**Comment by jstanden** [comment]
Thanks! I'll test that in my project right now and will report back.

**Comment by jstanden** [comment]
@singpolyma The hash/signer change looks good. I tested:

* Key generation from OpenPGP-PHP (2048/3072/4096, SHA-256/512) w/ subkeys.
* Thunderbird Key Manager import OpenPGP-PHP generated secret + public keys.
* `rnpkeys` CLI import OpenPGP-PHP generated secret + public keys.
* OpenPGP-PHP encrypted email to Thunderbird.
* OpenPGP-PHP signed email to Thunderbird.
* Thunderbird encrypted email to OpenPGP-PHP.
* Thunderbird signed email to OpenPGP-PHP.

**Comment by singpolyma** [comment]
Great! I've tagged 0.7.0

**Comment by jstanden** [comment]
@singpolyma Much appreciated! When you get a moment, can you also update Packagist for Composer? https://packagist.org/packages/singpolyma/openpgp-php

**Comment by singpolyma** [comment]
done
