### ISSUE TITLE
how can we store the encrypted data as ASCII

### ISSUE THREAD

**Issue by DanielRuf** [singpolyma/openpgp-php#14]
Is there some example? How do we use `OpenPGP_Crypt_Symmetric::encrypt` with `OpenPGP::enarmor`?

**Comment by singpolyma** [comment]
similar to https://github.com/singpolyma/openpgp-php/blob/master/examples/clearsign.php

Encrypt the message, then pass the result of `$message->to_bytes()` to enarmor

**Comment by DanielRuf** [comment]
The result produces a CMS error in GPA because the `BEGIN PGP MESSAGE` is not there.

But then GPA says there is no valid encrypted code.

```
$data = new OpenPGP_LiteralDataPacket('This is text.', array('format' => 'u', 'filename' => 'stuff.txt'));
$encrypted = OpenPGP_Crypt_Symmetric::encrypt($key, new OpenPGP_Message(array($data)));
$enc = OpenPGP::enarmor($encrypted->to_bytes());
$enc =  wordwrap($enc, 64, "\n", 1);
var_dump($enc);
```
