### ISSUE TITLE
Example for how to use asymmetric/public key encryption?

### ISSUE THREAD

**Issue by meitar** [singpolyma/openpgp-php#20]
I am trying to use this library for a trivial encryption using a public key and then a future decryption using the corresponding private key, but I am not sure how to do so with this library's API. I could not find an example for this (only for "symmetric" ciphers).

I also looked through [these Doxygen docs](https://singpolyma.github.io/openpgp-php/) but they are not clear to me.

Can you add an example for this case?

Thanks.

/cc @DanielRuf meitar/wp-pgp-encrypted-emails#3

**Comment by DanielRuf** [comment]
https://github.com/singpolyma/openpgp-php/issues/19

**Comment by meitar** [comment]
I've seen both of those, I think I understand what they are doing, and I tried following those examples [here](https://github.com/meitar/wp-pgp-encrypted-emails/blob/0fe11585e6e56b770a88a6886a0614591ff1da27/wp-pgp-encrypted-emails.php#L437), but the resulting ASCII-armored text does not decrypt with the correct key.

If those examples are supposed to encrypt a message with a public key and allow a corresponding private key to decrypt it, then I must have missed a step or two somewhere, but cannot see where.

**Comment by DanielRuf** [comment]
Will take a closer look at the code in about an hour and let you know, what the problem is.

**Comment by meitar** [comment]
Thanks, no rush.

**Comment by singpolyma** [comment]
This is the example: https://github.com/singpolyma/openpgp-php/blob/master/examples/encryptDecrypt.php

The one module is named "symmetric" because it is the nature of PGP's hybrid encryption that one part of it must be symmetric, but that example is of exactly what you want (encrypt to public key, decrypt with secret key)

**Comment by DanielRuf** [comment]
You should install the dependencies with composer and use the generated autoload file to include openpgp-php and phpseclib.

This code works for me
```php
require_once 'vendor/autoload.php';

$args['message'] = "test";

$ascii_key = "-----BEGIN PGP PUBLIC KEY BLOCK-----
*snip*
-----END PGP PUBLIC KEY BLOCK-----
";
$key = OpenPGP_Message::parse(OpenPGP::unarmor($ascii_key, "PGP PUBLIC KEY BLOCK"));

$plain_data  = new OpenPGP_LiteralDataPacket(
$args['message'],
array('format' => 'u', 'filename' => 'encrypted.gpg')
);

$encrypted = OpenPGP_Crypt_Symmetric::encrypt(
$key,
new OpenPGP_Message(array($plain_data))
);

$args['message'] = OpenPGP::enarmor($encrypted->to_bytes(), "PGP MESSAGE");

var_dump($args['message']);
```

**Comment by meitar** [comment]
In that case, there must be something wrong with my keys?

When I try decrypting, I get this:

```sh
$ gpg2 --list-packets /tmp/mytest 
:pubkey enc packet: version 3, algo 1, keyid B8D262DB28A917AA
	data: [2045 bits]

You need a passphrase to unlock the secret key for
user: "maymay <[…REDACTED…]>"
2048-bit RSA key, ID 28A917AA, created 2013-06-07 (main key ID 4DB88B59)

:pubkey enc packet: version 3, algo 1, keyid 0900E4EB4DB88B59
	data: [2048 bits]

You need a passphrase to unlock the secret key for
user: "maymay <[…REDACTED…]>"
2048-bit RSA key, ID 4DB88B59, created 2013-06-07

:encrypted data packet:
	length: 699
	mdc_method: 2
gpg: encrypted with 2048-bit RSA key, ID 4DB88B59, created 2013-06-07
      "maymay <[…REDACTED…]>"
gpg: public key decryption failed: Wrong secret key used
gpg: encrypted with 2048-bit RSA key, ID 28A917AA, created 2013-06-07
      "maymay <[…REDACTED…]>"
gpg: public key decryption failed: Wrong secret key used
gpg: decryption failed: No secret key
```

In other words, perhaps the encryption has worked, and there's something else wrong. However, if that's the case, I have no good guess as to what it might be.

I have double-checked the key fingerprints shown in the output above against the keys in my keyring and they match. This is expected, as I am using this public/private keypair on a daily basis without issue.

Any other ideas for things I should look into?

**Comment by meitar** [comment]
To be clear, this output is similar to what I get when I run the command `gpg2 --decrypt --passphrase-file /tmp/passphrase /tmp/mytest` and wherein the `/tmp/passphrase` file contains the correct passphrase for my private key, and `/tmp/mytest` contains the ASCII-armored encrypted output of the code in question, above.

**Comment by singpolyma** [comment]
I you use the example in the repo (which both encrypts and decrypts) using your key instead of helloKey, does that work ok your system?

**Comment by meitar** [comment]
> I you use the example in the repo (which both encrypts and decrypts) using your key instead of helloKey, does that work ok your system?

Well, maybe not. Here is what I did, step by step:

```sh
# First, I cloned the repo
git clone https://github.com/singpolyma/openpgp-php.git
cd openpgp-php/
# Then I installed composer locally
php -r "readfile('https://getcomposer.org/installer');" > composer-setup.php
php -r "if (hash('SHA384', file_get_contents('composer-setup.php')) === 'fd26ce67e3b237fffd5e5544b45b0d92c41a4afe3e3f778e942e43ce6be197b9cdc7c251dcde6e2a52297ea269370680') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); }"
php composer-setup.php
php -r "unlink('composer-setup.php');"
# Then I used composer to install the dependencies
php composer.phar install --no-dev
# Then I pasted my key into the tests/data directory
pbpaste > tests/data/mykey.pubkey
# Then I edited encryptDecrypt.php example to point to my key instead of 'helloKey.gpg'
# Note that my key is ASCII-armored, in case that matters?
vim examples/encryptDecrypt.php
# Then I tried running the example, but got this error at first:
$ php examples/encryptDecrypt.php 

Fatal error: Class 'phpseclib\Crypt\RSA' not found in /Users/maymay/src/openpgp-php/lib/openpgp_crypt_rsa.php on line 13
# So then I edited the example again to add the autoload.php file generated by composer
vim examples/encryptDecrypt.php
# And when I ran the example a second time, I got this output:
$ php examples/encryptDecrypt.php 
NULL
```

So maybe something *is* wrong on my system? But this seems unlikely because the PHP code in question, above, is running on a completely different system (a virtual machine).

**Comment by singpolyma** [comment]
Did you put your secret key in that file? (needed for decryption). Did you export in binary format? (which the example uses)

**Comment by meitar** [comment]
Just to be clear:

```sh
$ gpg2 --export-secret-keys maymay@riseup.net > tests/data/mykey.pubkey 
$ php examples/encryptDecrypt.php 

Fatal error: Call to a member function setEncryptionMode() on a non-object in /Users/maymay/src/openpgp-php/lib/openpgp_crypt_rsa.php on line 210
```

Then, to be doubly-sure, I tried to de-armor an ASCII file that contained both the public and private key, but got the same error:

```sh
# This time, mykeytest.asc was an ASCII-armored full export of both my public and private key
$ gpg2 --dearmor < tests/data/mykeytest.asc > tests/data/mykey.pubkey
$ php examples/encryptDecrypt.php 

Fatal error: Call to a member function setEncryptionMode() on a non-object in /Users/maymay/src/openpgp-php/lib/openpgp_crypt_rsa.php on line 210
```

Am I doing something wrong?

**Comment by DanielRuf** [comment]
This is just the private key, not the public key: https://www.gnupg.org/gph/en/manual/r887.html

For encryption, only the public key is used. For decryption, the private key.

**Comment by meitar** [comment]
> This is just the private key

Not the second time.

I'm aware that the public key is used for encryption and the private key for decryption. I have tried with only the public key, only the private key, and both the private and public key.

* In the case of only a public key, I get a `NULL` output.
* In the case of only a private key, I get a fatal error.
* In the case of both a public and a private key, I get a fatal error.

Both fatal errors are: `Call to a member function setEncryptionMode() on a non-object in …openpgp-php/lib/openpgp_crypt_rsa.php on line 210`

**Comment by DanielRuf** [comment]
Very interesting, because I can not reproduce this with my keys here.

**Comment by singpolyma** [comment]
A PGP private key contains the public key, so no issue there. If you look at the code it seems that probably convert_secret_key is returning a non-object (maybe NULL) -- are all keys RSA?

**Comment by DanielRuf** [comment]
> are all keys RSA?

This might be the issue, because we expect RSA keys in the code. Accoding to https://github.com/singpolyma/openpgp-php/issues/20#issuecomment-186596711 they should be using RSA. Elgamal or something else might be the issue?

**Comment by meitar** [comment]
@DanielRuf I recall that you fixed a bug in `php-gpg` (jasonhinkle/php-gpg#26) that was caused because of something strange that I did not understand with one of my keys. Could this be related?

> are all keys RSA?

Yes, 2048 bit RSA for both the main key and the subkey.

> Elgamal or something else might be the issue?

Nope….

Do you want to see a `--list-packets` output from the key file? (I don't *think* that's particularly sensitive info, is it?)

**Comment by singpolyma** [comment]
does the example work on your system with the helloKey that's in the repository?

**Comment by singpolyma** [comment]
Oh. Is the secret key still encrypted to a passphrase when exported? The example code assumes it's already been decrypted I think

**Comment by meitar** [comment]
> does the example work on your system with the helloKey that's in the repository?

Yes:

```sh
$ php examples/encryptDecrypt.php 
object(OpenPGP_Message)#26 (2) {
  ["uri"]=>
  NULL
  ["packets"]=>
  array(1) {
    [0]=>
    object(OpenPGP_LiteralDataPacket)#33 (6) {
      ["format"]=>
      string(1) "u"
      ["filename"]=>
      string(9) "stuff.txt"
      ["timestamp"]=>
      int(1455979048)
      ["tag"]=>
      int(11)
      ["size"]=>
      int(14)
      ["data"]=>
      string(13) "This is text."
    }
  }
}
```

> Oh. Is the secret key still encrypted to a passphrase when exported? The example code assumes it's already been decrypted I think

That might be it; I just tried to create a brand-new key without a passphrase and that one worked. This also works with the problematic (passphrase-protected) key when I remove the decryption part of the example. So that's working.

When I use this code:

```php
$key = OpenPGP_Message::parse(file_get_contents(dirname(__FILE__) . '/../tests/data/binarykeys'));
$data = new OpenPGP_LiteralDataPacket('This is EXAMPLE text.', array('format' => 'u', 'filename' => 'stuff.txt'));
$encrypted = OpenPGP_Crypt_Symmetric::encrypt($key, new OpenPGP_Message(array($data)));

file_put_contents('/tmp/encryptedoutput', $encrypted->to_bytes());
```

then I can decrypt the example like this:

```sh
$ gpg2 --decrypt /tmp/encryptedoutput
You need a passphrase to unlock the secret key for
user: "maymay <maymay@riseup.net>"
2048-bit RSA key, ID 28A917AA, created 2013-06-07 (main key ID 4DB88B59)

gpg: encrypted with 2048-bit RSA key, ID 4DB88B59, created 2013-06-07
      "maymay <maymay@riseup.net>"
gpg: encrypted with 2048-bit RSA key, ID 28A917AA, created 2013-06-07
      "maymay <maymay@riseup.net>"
gpg: encrypted with 2048-bit RSA key, ID 4DB88B59, created 2013-06-07
      "maymay <maymay@riseup.net>"
gpg: encrypted with 2048-bit RSA key, ID 28A917AA, created 2013-06-07
      "maymay <maymay@riseup.net>"
This is EXAMPLE text.
```

My passphrase is already cached so the output is correct.

Thank you for the assistance. It turns out the error was indeed mine. Apologies for the trouble.

**Comment by DanielRuf** [comment]
@meitar Decryption of a secret / private key with password should be possible with `OpenPGP_Crypt_Symmetric::decryptSecretKey($pass, OpenPGP_SecretKeyPacket $keyEncrypted);`

https://github.com/singpolyma/openpgp-php/blob/6075d057d012c9ce466313a614f2e7ad26a6b01e/examples/deASCIIdeCrypt.php#L19

But did not test this myself as I always use `gpg` on the command line on the PC or GPA or Enigmail for decryption for several reasons.

**Comment by meitar** [comment]
Ah, thank you again @DanielRuf, I missed that.

**Comment by theresel82** [comment]
hi,
I've been looking on the net and this thread sounds like the closest thing that matches our scenario:

We would like to set up keys on a server (with a passphrase for the private key), encrypt data with the public key, and prompt the end-user for the passphrase in order to decrypt the encrypted data. (There is no need for emails)

I had first tried with gnuPG, but it turns that out that since version 2 it can only decrypt without passphrases, so am now looking for another solution.

Do I understand correctly that openPGP might allow this ?

thank you!

**Comment by singpolyma** [comment]
You want to encrypt to a public key and then decrypt using a (password protected) secret key?  Yes, any OpenPGP implementation (including this library) should certainly allow this.

**Comment by theresel82** [comment]
Yes - Is the sample code encryptDecrypt.php (plus the most recent comment from Daniel referring to OpenPGP_Crypt_Symmetric::decryptSecretKey) the best way to start?

**Comment by singpolyma** [comment]
@theresel82 yeah, encryptDecrypt.php + decryptSecretKey is probably the place to start :)

**Comment by theresel82** [comment]
thanks!
