### ISSUE TITLE
Encrypt attachments for use in emails?

### ISSUE THREAD

**Issue by meitar** [singpolyma/openpgp-php#21]
Can I use `openpgp-php` to encrypt files ("attachments") as part of a message?

(This is [a requested feature users want me to add to a tool that uses this library](https://wordpress.org/support/topic/encrypt-e-mail-attachments?replies=1), but I'm unsure how to go about using the library to do this.)

**Comment by singpolyma** [comment]
Yes, you will need to implement https://tools.ietf.org/html/rfc3156 yourself, though, as I don't have that in here yet. You should be able to use the encryption and enarmoring functions from this library to create the pieces needed for the encoding

**Comment by meitar** [comment]
Okay, thank you for the pointer! :) This is not something I can do myself quickly because I am not skilled enough but it is a good excuse/exercise to improve.

**Comment by DanielRuf** [comment]
https://github.com/DanielRuf/honeypot-scripts/blob/7a8b0daf5d57f27ab9ab164e6672af490d07b472/upload_mail.php#L30-L41

Just in case someone else stumbles into this issue here. ;-) You should not implement this yourself.

**Comment by singpolyma** [comment]
@DanielRuf No one said anything about S/MIME.

**Comment by singpolyma** [comment]
@DanielRuf The example you pasted looks like it's separately encrypting each attachment and attaching encrypted files. Unless I'm misreading the code, which I might be.  PGP/MIME will provide a much better user experience.

**Comment by DanielRuf** [comment]
Okay, but so far this should work with my example code which just uses another library (but already tested it with openpgp-php and it worked).
