### ISSUE TITLE
Crypt_RSA namespace in keygen example not available (out of scope)

### ISSUE THREAD

**Issue by DanielRuf** [singpolyma/openpgp-php#23]
It seems we have to use the full qualified name or redeclare the namespace in the test file / parent file as the generated classmap of the composer autoloader does not have a Crypt_RSA namespace declared.

https://github.com/singpolyma/openpgp-php/blob/d37e91efdae960582b7932cf2be7d59c1894c3b1/examples/keygen.php#L6

See https://github.com/meitar/wp-pgp-encrypted-emails/issues/1#issuecomment-187620758

http://stackoverflow.com/a/33378909/753676

It seems this was the case in the 1.0 branch of phpseclib but this library uses the 2.0 branch of phpseclib and this has changed since then as 2.0 is namespaced and so the API has changed.

**Comment by singpolyma** [comment]
Oh, I see, this is just for that one example because that's where we use the phpseclib code directly?  Could you send a pull request?

**Comment by DanielRuf** [comment]
It seems so.

Will so later today.

Maybe you can assist here but I will also do answer there regarding the verification issue later today when I find the time. https://github.com/meitar/wp-pgp-encrypted-emails/issues/1#issuecomment-187716181
