### ISSUE TITLE
how to enarmor keypair for import

### ISSUE THREAD

**Issue by DanielRuf** [singpolyma/openpgp-php#26]
Currently I have this code.

Did I miss some step there?

```php
require 'vendor/autoload.php';
require_once dirname(__FILE__).'/lib/openpgp.php';
require_once dirname(__FILE__).'/lib/openpgp_crypt_rsa.php';
$rsa = new \phpseclib\Crypt\RSA();
$k = $rsa->createKey(2048);
$rsa->loadKey($k['privatekey']);
$nkey = new OpenPGP_SecretKeyPacket(array(
   'n' => $rsa->modulus->toBytes(),
   'e' => $rsa->publicExponent->toBytes(),
   'd' => $rsa->exponent->toBytes(),
   'p' => $rsa->primes[1]->toBytes(),
   'q' => $rsa->primes[2]->toBytes(),
   'u' => $rsa->coefficients[2]->toBytes()
));
$uid = new OpenPGP_UserIDPacket('Test <test@example.com>');
$wkey = new OpenPGP_Crypt_RSA($nkey);
$m = $wkey->sign_key_userid(array($nkey, $uid));
// Serialize private key
//print $m->to_bytes();
// Serialize public key message
$pubm = clone($m);
$pubm[0] = new OpenPGP_PublicKeyPacket($pubm[0]);
$public_bytes = $pubm->to_bytes();
var_dump(OpenPGP::enarmor($m->to_bytes(), "PGP PRIVATE KEY BLOCK"));
var_dump(OpenPGP::enarmor($public_bytes, "PGP PUBLIC KEY BLOCK"));
```

**Comment by singpolyma** [comment]
You have these inverted. `$public_bytes` is the public key and `$m->to_bytes()` is the private key.

Also, using `var_dump` here doesn't really make sense.  Also the private key contains the public key, so no need to import them both into the same program.  Also you are still printing out the binary in your example, which might be affecting you.

**Comment by DanielRuf** [comment]
Makes no change, still getting "BER error" when importing just the private key (and also public key).

**Comment by singpolyma** [comment]
But is var_dump not likely to be munging the string a bit?  You should echo the string directly.

**Comment by DanielRuf** [comment]
No difference here, still "BER error".

**Comment by DanielRuf** [comment]
Works here now. I have to check what is wrong with the other system, wasn't acting like this before (it is definitely clean).
