### ISSUE TITLE
generated key just has verification flag in GPA

### ISSUE THREAD

**Issue by DanielRuf** [singpolyma/openpgp-php#27]
Like @meitar already mentioned, there is something with the keypair after importing it.

https://github.com/meitar/wp-pgp-encrypted-emails/issues/1#issuecomment-188223173

> After doing a little more diging my guess is that the generated keypair only contains the c (certify) capability, but not the s (sign) capability. I checked this by importing the keys into a GUI and inspecting the key there. (Screenshot attached.)

After importing the generated keypair, GPA just shows the private key and this has just the cert capability, but why?

Manually generated keypairs using gpg and GPA have a private and a public key with the right capabilities.

http://unix.stackexchange.com/questions/31996/how-are-the-gpg-usage-flags-defined-in-the-key-details-listing

**Comment by DanielRuf** [comment]
Possibly related to this: http://stackoverflow.com/questions/35633351/cant-decrypt-file-encrypted-with-openpgp-php-in-gnupg

Confirmed, this does not work here. Decryption fails (no valid encrypted PGP data) and encryption also (throws exception and crashes GPA).

**Comment by DanielRuf** [comment]
Any update about this problem @singpolyma?

**Comment by DanielRuf** [comment]
I have tracked it down to these lines

The values from here seem to not be properly added, just the first value is actually used

https://github.com/singpolyma/openpgp-php/blob/ff4bd67e6be861401e0f577332c64c0ea8990d7b/lib/openpgp_crypt_rsa.php#L157

All values are processed

https://github.com/singpolyma/openpgp-php/blob/cefaef242df6bdb85e19bcf0c23e4fff697737c9/lib/openpgp.php#L1194

Also the public key is not shown in GPA, just the private key.

**Comment by DanielRuf** [comment]
@meitar importing the public key should be possible with `--allow-non-selfsigned-uid` see http://stackoverflow.com/questions/35633351/cant-decrypt-file-encrypted-with-openpgp-php-in-gnupg

I will take a look again at the code and the issue with the flags and provide a PR if possible.

**Comment by meitar** [comment]
@DanielRuf Okay, but I'm not having any trouble importing the public key. It's generating a revocation certificate that I'm having trouble with (see above reference). :\

**Comment by singpolyma** [comment]
Please test my latest version with https://github.com/singpolyma/openpgp-php/commit/741fec24a6a31d6eb4844b15d5bcecad09e1b53d and see if this helps you.

**Comment by meitar** [comment]
@singpolyma The newest commits *do* create a key with the S (signing) capability. The previous keys generated with this library were created with only the C (certify) capability. So that's definitely a fix, as intended.

However, as per @DanielRuf's question, this does *not* resolve the issue with manually creating a revocation certificate (described in #31). These latest commits do not affect that issue at all.

**Comment by singpolyma** [comment]
@meitar are you using the example script to do they keygen? I specifically refer to the commit that fixes the keygen example to use the correct p/u values. This changed fixed revocation generation for me in gpg locally.

**Comment by meitar** [comment]
> I specifically refer to the commit that fixes the keygen example to use the correct p/u values.

Ah!! I'm sorry, I was looking only at commits in `lib` and the dependencies.

You're right, using the correct p/q values enables me to create a revocation certificate as well. Thank you!
