### ISSUE TITLE
Confirming which repo to use?

### ISSUE THREAD

**Issue by trogau** [singpolyma/openpgp-php#30]
Hi,

Not a real issue, just a question: the home page referred to in the README (http://singpolyma.github.io/openpgp-php/) points to @bendiken's repo as the official repo for this project (i.e., https://github.com/bendiken/openpgp-php). But at a glance it seems like this one is actually current & should probably be used?

Thanks,

**Comment by DanielRuf** [comment]
The repository of @bendiken is outdated, see the date of the latest commit https://github.com/bendiken/openpgp-php/commits/master

This one here (the fork) should be preferred over the original.

**Comment by singpolyma** [comment]
I've always considered @bendiken to be upstream, but it's true that his repo does not see updates often anymore and this fork is much more active.
