### ISSUE TITLE
Loosen phpseclib dependency

### ISSUE THREAD

**Issue by yunosh** [singpolyma/openpgp-php#34]
The phpseclib dependency should be set to "^2.0" instead of "2.0.0", or is there any reason for the strict requirement?

**Comment by singpolyma** [comment]
Does it work if you test it with later versions (by work, I mean at least all tests pass)?

**Comment by RobvH** [comment]
With phpseclib/phpseclib 2.0.2 -- YES.

**Comment by singpolyma** [comment]
This is done now.
