### ISSUE TITLE
Serialization::testpubringgpg fails

### ISSUE THREAD

**Issue by yunosh** [singpolyma/openpgp-php#35]
[log.txt](https://github.com/singpolyma/openpgp-php/files/347841/log.txt)

**Comment by yunosh** [comment]
Fresh Git checkout, dependencies pulled in with current composer.json.

**Comment by singpolyma** [comment]
Everything passes locally, and on CI: https://travis-ci.org/singpolyma/openpgp-php/builds/116106520 (the nightly failure is related to changes in the mcrypt API that are not a problem for any released PHP).  Not sure what's wrong in your setup.

**Comment by yunosh** [comment]
I can reproduce this on two Ubuntu Xenial systems, one with, one without mcrypt and gmp extensions. Both without libsodium.

**Comment by yunosh** [comment]
Installing libsodium doesn't make a difference either.

**Comment by singpolyma** [comment]
What PHP version?  Is it a version I don't have in the TravisCI config yet?

**Comment by singpolyma** [comment]
Also: what CPU architecture?

**Comment by yunosh** [comment]
PHP version 7.0.8 (-0ubuntu0.16.04.1 FWIW)
Linux tank 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by singpolyma** [comment]
If you try latest master, does it work?  There were some issues with different versions of phpseclib and the versions have now been restricted to ones which pass CI.

**Comment by yunosh** [comment]
No difference, I had phpseclib 2.0.2 installed anyway.
