### ISSUE TITLE
How can I verify user input?

### ISSUE THREAD

**Issue by michaelpittino** [singpolyma/openpgp-php#36]
Hello! I'm quite new to this pgp stuff and I want to verify a user's public key.
For example he could enter:

```
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: BCPG C# v1.6.1.0

mQENBFe2fVoBCACDfYZyaLMbT9RdOGBeVdukrOEp7zAMZbSEJUThNmNIqePrkcTs
XCNDo2VsgEim3Y4vwTcWuFu3cLJUZTUD3zLTol7j/JgwiOofQ0cWNMZwUX5L+Ma3
oSHCvHuIkdJ3NrNzOXcz8NFszR+imfA/Pgx1QbXECGH0CJrOe0h1s7la25FM8Z3K
H66jlrRTxOmwnUVaOOtBvqrSEMSa6pT/nt3phqL4AaSj+nB2O0M/Hi7UJ3kpsQ5O
njoad268T1s31aIxxrAce0HyqKuq2MBHCQxsXdHunoekbT2VyV9ty5fAVjFQ9orS
k9gZjp7IlhHIt0K6Cgp3yUk+fXv05mFOR14fABEBAAG0CHRlc3RAdHN0iQEcBBAB
AgAGBQJXtn1aAAoJEHYjgb+PDHndt7YH/1DXG+kRpfMw8nJhn5fhLLBEgLyRWiYg
J90YZxOv8OtgUv2hdEUO8oWFzT5R6+tdrklLEAtsbJ7/y1TuTPegCr2HLnas+rlq
JrBhUVhaGD03zTLdakUCmX/5KeYRu58YGvz9+UW10zrMhzA4juy8Ua06eADAUsFx
mUeJeHB1IPTwxH21F6zxxJSx95Id9HZvaKknvhYP/vMYC0V/kLuzyhtkwBZ/Oinx
iTqh7TbegA/cb++vxOxjAmO5uZKG54E/vsoXWQcz8dM4aQ4WPKCWPEH4qL/Rqs/M
9dQdxgqrSNL1QyD+/1cUD06+5Ld6w0ObwtVJaS2tle69FOG4+sCV1MY=
=751J
-----END PGP PUBLIC KEY BLOCK-----
```

Or: `jaskdhasjdhasdas`

Of course the second input wouldn't be a valid public key.
How can I verify this?

Thanks in advance!

**Comment by singpolyma** [comment]
You could feed it into `OpenPGP_Message::parse` and see if the resulting packet stream contains a key or not (or if it's totally empty, that would mean no valid input).

**Comment by axelay** [comment]
I tried to do as suggested with this key:
```
-----BEGIN PGP PUBLIC KEY BLOCK-----

-----END PGP PUBLIC KEY BLOCK-----
```
And the result comes back as:
```
OpenPGP_Message Object
(
    [uri] => 
    [packets] => Array
        (
            [0] => OpenPGP_LiteralDataPacket Object
                (
                    [format] => -
                    [filename] => BEGIN PGP PUBLIC KEY BLOCK-----

-----END P
                    [timestamp] => 1196433488
                    [tag] => 11
                    [size] => 21
                    [data] => UBLIC KEY BLOCK-----
                )
        )
)
```

Is there a better way to validate the input?

**Comment by axelay** [comment]
Answered my own question by using:
$wkey = OpenPGP_Message::parse(OpenPGP::unarmor($pgpkey, 'PGP PUBLIC KEY BLOCK'));

The I have to check if the packets OpenPGP_UserIDPacket and OpenPGP_PublicKeyPacket are present - if not then the key is invalid.
I hope this is the way to do it

**Comment by singpolyma** [comment]
Depending on your use case you likely also want to check the self-signature on the userid

**Comment by axelay** [comment]
I just need to check the PGP Key entered by the user is valid - no need to do further checks other than validating it's a proper key.
Thanks for getting back to me
