### ISSUE TITLE
Minor issue in keygen.php example

### ISSUE THREAD

**Issue by cgraefe** [singpolyma/openpgp-php#38]
When trying to run the keygen.php example I am getting
`[Error] Cannot use object of type OpenPGP_SecretKeyPacket as array`

I haven't had time to look into this in every detail, but could it be that line 29 should actually be changed like this?

```
- $pubm[0] = new OpenPGP_PublicKeyPacket($pubm[0]);
+ $pubm[0] = new OpenPGP_PublicKeyPacket($pubm[0]->key);
```

**Comment by singpolyma** [comment]
If you try with latest master, does it work for you?  I've pushed a restriction on the versions of phpseclib supported due to similar issues in other places.
