### ISSUE TITLE
Is this Repository Supported

### ISSUE THREAD

**Issue by jgallavin** [singpolyma/openpgp-php#44]
The latest commit is on Jul 26, 2016 and the latest release is on Aug 14, 2015.

There are several tests that are failing due to the decrypt method on the lastest commit.

Does the encrypt method work or does it not work and decrypt is failing as a result?

The last release does not support php 7.1 It would be important to create another stable release for this package to last. This package is the only autoloaded open pgp library out there.

Thanks,
Jason Gallavin

**Comment by singpolyma** [comment]
I don't think I ever made a release, did I? It's possible I merged a PR that broke a test, or more likely that it's a dependency issue? I haven't worked on it much recently, but happy to take PRs still at very least :)

**Comment by jgallavin** [comment]
There was a release of 0.2.0. All the tests pass but it doesn't work in php 7.1 because it is using an old version of phpseclib. 

I am trying to figure out what is wrong with the tests on master. I am no PGP expert so it's pretty difficult. 

It seems to be the problem with the decrypt method. It is possible that phpseclib is getting called wrong now that it is using a new version. 

Call to a member function equals() on string
 C:\projects\work\openpgp-php\vendor\phpseclib\phpseclib\phpseclib\Crypt\RSA.php:2091
 C:\projects\work\openpgp-php\vendor\phpseclib\phpseclib\phpseclib\Crypt\RSA.php:2264
 C:\projects\work\openpgp-php\vendor\phpseclib\phpseclib\phpseclib\Crypt\RSA.php:2779
 C:\projects\work\openpgp-php\vendor\phpseclib\phpseclib\phpseclib\Crypt\RSA.php:2987
 C:\projects\work\openpgp-php\lib\openpgp_crypt_rsa.php:130
 C:\projects\work\openpgp-php\lib\openpgp.php:679
 C:\projects\work\openpgp-php\lib\openpgp_crypt_rsa.php:130
 C:\projects\work\openpgp-php\tests\phpseclib_suite.php:37

Any pointers for trying to figure this out?

I am running these tests in php 7.0 to try and narrow down the issue.

**Comment by jgallavin** [comment]
Okay after hopping through each version I found that commit 6d9ed34224cc23d466d474c0e8bd23947ce5fe34 "Less strict phpseclib requirement" causes the tests to fail. 
If you could make a release on the commit before de41f143e62346f2b1fce2ede32f06b860734f33 "Throw exception if using CAST5 without mcrypt" then we should have a working php 7.1 release.

**Comment by jgallavin** [comment]
I have not tested below 7.1 and 7.0 however. I should be able to tests those later today

**Comment by singpolyma** [comment]
@jgallavin if you instead take HEAD and edit `composer.json` to depend on exactly phpseclib `2.0.0` does that also work for you?

**Comment by singpolyma** [comment]
Alright, it seems the problems started with the release of `2.0.3`  I am going to push a commit soon which changes the version restriction for now until the breaking change can be identified.

**Comment by singpolyma** [comment]
I'll chat with upstream about this https://github.com/phpseclib/phpseclib/issues/1113

**Comment by jgallavin** [comment]
I can confirm the latest commit works with  phpseclib 2.0.0.

**Comment by singpolyma** [comment]
Perfect, thanks. I've merged the new version constraints, so you should be able to use master again now :)

**Comment by jgallavin** [comment]
Can we make this a release to packagist? Everything seems to be working.

**Comment by singpolyma** [comment]
what is packagist? Can you just depend on the github directly?

**Comment by jasekiw** [comment]
Your package is already on packagist. It has over 2k installs there. It would be important to release to packagist along with the repo. composer require singpolyma/openpgp-php will install the old version and not have the updated phpseclib.

https://packagist.org/packages/singpolyma/openpgp-php
