### ISSUE TITLE
Release a new version to packagist

### ISSUE THREAD

**Issue by jasekiw** [singpolyma/openpgp-php#47]
This repo is registered in packagist  and gets a good amount of traffic.

https://packagist.org/packages/singpolyma/openpgp-php/stats

We should release the update that fixes the compatibility with phpseclib 2.0.3 so 
composer require singpolyma/openpgp-php will install the updated version.

The owner of the package is "vstm" however.

**Comment by singpolyma** [comment]
I've created a new tag... maybe packagist will find it automatically?

**Comment by jasekiw** [comment]
I believe you have to tell packagist to rescan the repo when you create a new tag. There is a way for it to automatically check but it has to be set up.

**Comment by jasekiw** [comment]
If the owner of the package is not you I suggest that you contact packagist to gain ownership of the package. If you do not have the time I can contact them for you and try to handle it.

**Comment by singpolyma** [comment]
I've emailed them

**Comment by jasekiw** [comment]
Awesome! I hope it works.

**Comment by singpolyma** [comment]
done
