### ISSUE TITLE
EXAMPLE PLEASE!!!

### ISSUE THREAD

**Issue by krisidmisso** [singpolyma/openpgp-php#49]
Can you please post a full example using public key, private key, PASSPHRASE and message... both for encryption end decryption.
Thank you

**Comment by singpolyma** [comment]
https://github.com/singpolyma/openpgp-php/blob/master/examples/encryptDecrypt.php

Shows encrypt/decrypt using a key. To use a passphrase instead, send the encrypt function an array containing strings. Or you can do both passphrases and keys by mixing them in the array.

**Comment by krisidmisso** [comment]
Can you please give me a full example for my case?
1. I want to generate a public and private key based on a keypair (EMAIL + PASSPHRASE or just passphrase)
2. Encrypt a message (TEXT, not file. When i ::parsestring public key from keygen i get an error) using public key generated from step 1
3. Decrypt message using private key and PASSPHRASE from step 1

Thank you again for the reply

**Comment by Hoffstadt** [comment]
This might help you, assuming you already have your way of generating keys:

[Test Example](https://gist.github.com/Hoffstadt/51695400fd4fc65f50b0802d603bd1f0)

I have set up an example in a unit test file you can place in your project and play around with.

@krisidmisso 

@singpolyma You might want to change the example to draw from separate sources for the public and private key to make the example more obvious. I got confused by the "OpenPGP_Crypt_Symmetric" for a sec, too.

Regards
Hoffstadt

**Comment by singpolyma** [comment]
> Shouldnt Encryption use the public key, and decryption dhe private key??

Every OpenPGP secret key contains a full copy of the public key, so if you happen to have the secret key in memory already you can use to for encryption to save a step, which is what the example is doing.  Of course, if you only have the public key then you can use that for encryption just fine as well.

**Comment by kglazov** [comment]
How can I convert binary encryption to ascii?

**Comment by elhawy** [comment]
@singpolyma i  had generated public and private key for test from [https://pgpkeygen.com/](url) 
while decrypting message it always throw 

```
ErrorException {#1227
  #message: "Undefined index: d"
  #code: 0
  #file: "vendor/singpolyma/openpgp-php/lib/openpgp_crypt_rsa.php"
```

with my private key i did not know why convert_key function celled

**Comment by elhawy** [comment]
@singpolyma i  had generated public and private key for test from [https://pgpkeygen.com/](url) 
while decrypting message it always throw 

```
ErrorException {#1227
  #message: "Undefined index: d"
  #code: 0
  #file: "vendor/singpolyma/openpgp-php/lib/openpgp_crypt_rsa.php"
```

with my private key i did not know why convert_key function celled

**Comment by singpolyma** [comment]
This issue is attracting unrelated questions and the original question I believe has been answered, so I'm going to close it for now.  If the original poster believes the question is not answered, please comment to reopen.  Others can open new issues for new questions, please.
