### ISSUE TITLE
D index of array

### ISSUE THREAD

**Issue by pgogy** [singpolyma/openpgp-php#5]
Hello
https://github.com/singpolyma/openpgp-php/blob/master/examples/sign.php
I am using this, but when I try to sign, I get a notice that the D index doesn't exist?
I suspect my key is still password protected - can you suggest a way around that?
Thanks so much for the code
Pat

**Comment by singpolyma** [comment]
If you look at https://github.com/singpolyma/openpgp-php/blob/master/examples/deASCIIdeCrypt.php you can see example code for de-ascii and de-crypting a secret key -- in this example it is then used for decrypting, but you could change that to do signing afterwards.

**Comment by pgogy** [comment]
Much appreciated, thank you

**Comment by pgogy** [comment]
Thanks
