### ISSUE TITLE
Class 'phpseclib\Crypt\RSA' not found

### ISSUE THREAD

**Issue by Arinerron** [singpolyma/openpgp-php#50]
```
PHP Fatal error:  Class 'phpseclib\Crypt\RSA' not found in openpgp-php/lib/openpgp_crypt_rsa.php on line 13
```

Are there dependencies I'm missing?

**Comment by singpolyma** [comment]
How did you install it? You need phpseclib >=2.0.0

**Comment by Arinerron** [comment]
I `git clone`d

**Comment by jasekiw** [comment]
please run composer install to install the dependencies. composer - https://getcomposer.org/

**Comment by Oros42** [comment]
I have got the same error.

This is who I solved it :
```bash
git clone https://github.com/singpolyma/openpgp-php
cd openpgp-php
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php composer-setup.php
php -r "unlink('composer-setup.php');"
php composer.phar install
```
And put in ./lib/openpgp.php at line 16, this :
```php
include "../vendor/autoload.php";
```

**Comment by DanielRuf** [comment]
You should use the autoload file in your own project. Generally this is exactly what is written in the comments before your answer.

**Comment by saiddddd** [comment]
hahahahah
