### ISSUE TITLE
Decrypting PGP message

### ISSUE THREAD

**Issue by ukmasa** [singpolyma/openpgp-php#51]
Hi Stephen, thanks for making openpgp-php available.
I have had a few issues with decrypting a PGP message using my PGP key.  I followed the example encryptDecrypt.php, but it did not work for me.  I had to write following code, which seems to work:

`    	$msg = OpenPGP_Message::parse(OpenPGP::unarmor($pgp_message, 'PGP MESSAGE')); // Parse PGP message 
    	$keyEncrypted = OpenPGP_Message::parse(OpenPGP::unarmor($pgp_priv_key, 'PGP PRIVATE KEY BLOCK')); // Parse  private key     	
    	$plain_text = '';

    	// Try each secret key packet to find secret key packet
    	foreach($keyEncrypted->packets as $p) 
    	{
    		if(get_class($p) != 'OpenPGP_SecretSubkeyPacket') continue;    	// If Not right packet type
    		
			$nkey = new OpenPGP_SecretKeyPacket($p->key); // Load PGP private key to decrypt PGP message 
			$decryptor = new OpenPGP_Crypt_RSA($nkey);  // Initialise decryptor with PGP private key
			$decrypted = $decryptor->decrypt($msg); //  OpenPGP_Message Object	    	
	    	
	    	// Search for OpenPGP_LiteralDataPacket object which contains decrypted plaintext
    		foreach($decrypted->packets[0]->data->packets  as $obj)
    		{	
    			if($obj instanceof OpenPGP_LiteralDataPacket)
    			{
    				$plain_text = $obj->data;
    				break;
    			}
    		}
    		break;
    	}
    	
    	
    	return $plain_text;
`

**Comment by singpolyma** [comment]
Looks very similar to https://github.com/singpolyma/openpgp-php/blob/master/examples/deASCIIdeCrypt.php

**Comment by ukmasa** [comment]
Sorry, I was doing something wrong and fixed it, so I closed this issue
