### ISSUE TITLE
Displaying message

### ISSUE THREAD

**Issue by lukaisailovic** [singpolyma/openpgp-php#54]
Hey, I'm successfully encrypting a message like this:
```
$encrypted = OpenPGP_Crypt_Symmetric::encrypt(
                $key,
                new OpenPGP_Message(array($data))
            );
```

And I'm left with an instance of OpenPGP_Message . How can I display this message to someone now in order to have it decrypted by user?

**Comment by singpolyma** [comment]
call `to_bytes` on the message. Use then ASCII armour helpers also if you want that.

**Comment by lukaisailovic** [comment]
@singpolyma  When using `to_bytes `I get `Undefined property`. And what is the ASCII armour helper ? I've looked over the examples but cannot find it

**Comment by singpolyma** [comment]
At a glance, your code looks like the right idea to me. Do you get an error from your decrypt attempt, or just no data?

**Comment by lukaisailovic** [comment]
Well I'm trying to have some data encrypted for users for decrypt on their computes. When I try to decrypt it I'm just getting No data in gpg4usb and kleopatra could not determine the type. So no idea what is going on here

**Comment by singpolyma** [comment]
so are you getting errors? Could you screenshot the error?

**Comment by lukaisailovic** [comment]
Okay, I've used multiple clients now and these are messages I'm getting when trying to decrypt message with each one of them: (every client have my private key imported):
pgp4usb - No data error https://image.prntscr.com/image/_e9N6VrJRfirdKqzocIvXQ.png
kleopatra - https://image.prntscr.com/image/L2iacnFsRQmRtLPji4PYPg.png

**Comment by singpolyma** [comment]
Could you also paste the output you tried to feed these programs for decryption?

**Comment by lukaisailovic** [comment]
Fixed it. It was a spacing problem. When you just echo output it does not create right spacing. You have to put it in something like textarea

**Comment by grcasanova** [comment]
I'm using the exact same code but can't decrypt it, plus every time I run it a totally different message is generated (the resulting messages have different character sequences).

```
        $key = OpenPGP_Message::parse(
            OpenPGP::unarmor($pubkey, 'PGP PUBLIC KEY BLOCK')
        );
        $message = 'Hello World';
        $data = new OpenPGP_LiteralDataPacket($message);
        $encrypted = OpenPGP_Crypt_Symmetric::encrypt(
                $key,
                new OpenPGP_Message(array($data))
        );

        $armored = OpenPGP::enarmor($encrypted->to_bytes(),'PGP MESSAGE');
        echo $armored;
```

**Comment by singpolyma** [comment]
A different encrypted output every time is expected, since there are usually timestamps etc.

If you get an error trying to decrypt something made with that code, what error do you get?
