### ISSUE TITLE
possible mcrypt replacement - libsodium

### ISSUE THREAD

**Issue by jasekiw** [singpolyma/openpgp-php#55]
PHP 7.2 is coming with [sodium](https://github.com/jedisct1/libsodium-php) baked in. Maybe this could be used as a replacement for mcrypt that was removed in PHP 7.1.
 
Since this project relies on mcrypt is sodium a possible replacement in this project or do they accomplish different things?

**Comment by singpolyma** [comment]
sounds worth investigating!

**Comment by jasekiw** [comment]
@singpolyma What learning resources do you recommend for learning how to contribute to this library?

**Comment by singpolyma** [comment]
@jasekiw if you want to learn more about the spec and fine the main one daunting, I've distilled some of the most necessary parts to https://github.com/singpolyma/openpgp-spec

If you're interested into helping with this mcrypt issue specifically, the mcrypt-using code is isolated to one file that's designed to be modular (so you could write another file with the same interface using libsodium, IIRC)

**Comment by singpolyma** [comment]
Looking over the code again, I think it only uses mcrypt for CAST5 support.

**Comment by jasekiw** [comment]
After looking at libsodium  more closely it seems that PHP will add it to the core extensions in PHP 7.2. However you can install the extension on 7.0+. So that leaves 7.1 completely unsupported and breaks < 7.0. I see two paths to go down. 

1. Create a legacy branch to support < 7.0 with mcrypt and implement libsodium. This would require a version jump since the drop of support would be quite large. The only supported version that is dropped is PHP 5. This package would also require the installation of libsodium on php versions < 7.2.

2. Investigate what methods use CAST5 and see if we can remove mcrypt without replacing it with libsodium. is CAST5 operations necessary? This has the pros of supporting older versions of PHP as well as newer.

**Comment by singpolyma** [comment]
CAST5 is only necessary if you need to interoperate with someone using it as their symmetric algorithm. Unfortunately, gnupg defaults to CAST5 in most versions, so such interoperation is often desired.

**Comment by singpolyma** [comment]
Probably the best is to have compatible mcrypt and sodium wrappers in the library, and choose the right one a runtime based on what is installed, to keep compatibility with both popular and new versions of PHP.

**Comment by jasekiw** [comment]
I didn't think of that. That would be way better. PHP 7.1 would still be an odd version for people to install the package because the user would have to install libsodium seperately.

I cannot seem to find documentation on how to perform a CAST5 operation using libsodium. Have you seen anything?

I also found CAST5 in the list of supported algorithms in [openssl](http://php.net/manual/en/function.openssl-get-cipher-methods.php). Maybe OpenSSL can be a polyfill?

**Comment by singpolyma** [comment]
I think sodium calls it cast128 -- same algorithm

**Comment by DanielRuf** [comment]
Why not use https://github.com/paragonie/sodium_compat?

**Comment by jedisct1** [comment]
The PECL extension supports PHP 7.0.x, 7.1.x and 7.2.x

**Comment by DanielRuf** [comment]
> The PECL extension supports PHP 7.0.x, 7.1.x and 7.2.x

This is not an option here as this library should work on all systems with the right polyfills afaik.

**Comment by Rotzbua** [comment]
You can use `openssl` for encryption and signing. Only Idea and Twofish is not supported with openssl. (Only tested with php7.0)

**Comment by DanielRuf** [comment]
> You can use openssl for encryption and signing. Only Idea and Twofish is not supported with openssl. (Only tested with php7.0)

No, this should not be done.

**Comment by Rotzbua** [comment]
> No, this should not be done.

Why?

Mcrypt is used in this library for encrypting with `cast5`. Openssl supports `cast5`. -> Openssl can replace Mcrypt.

**Comment by DanielRuf** [comment]
We should use and move to libsodium.

**Comment by DanielRuf** [comment]
Because it makes no sense to reimplement mcrypt with openssl and libsodium is different. mcrypt support should be dropped in the future.

**Comment by Rotzbua** [comment]
@DanielRuf https://github.com/paragonie/sodium_compat#cryptography-primitives-provided do not list cipher `cast5`. Where did you read that the sodium library supports cipher `cast5`?

**Comment by DanielRuf** [comment]
Did I say so?

**Comment by DanielRuf** [comment]
Also see the comment og singpolyma

> I think sodium calls it cast128 -- same algorithm

**Comment by Rotzbua** [comment]
> Did I say so?

More ore less, yes. You wrote:

> We should use and move to libsodium.

So you have no clue about the sodium library, but you recommend it. No words...

@singpolyma Sodium do not support any cipher used by openpgp. https://secure.php.net/manual/en/ref.sodium.php

**Comment by singpolyma** [comment]
I'm happy to accept wrappers for any of openssl or sodium or whatever else for cast5/cast128 support. Should be no problem to support all of these options and use whatever is available on the system we're running on.

**Comment by DanielRuf** [comment]
@Rotzbue initially it was not my recommendation. See the first comment. I just said that I am also for supporting libsodium in some way.

I never wrote that it supports the gnupg / pgp algorithms ;-)

**Comment by DanielRuf** [comment]
Writing pure openssl wrappers is like writing your own crypto which is not recommended. I guess there is already a library for this eg by paragonie, ircmaxell and others.

**Comment by jedisct1** [comment]
libsodium does not support CAST5. In fact, in doesn't support any of the ciphers currently supported by GnuPG. So, files encrypted using OpenPGP-PHP could only be decrypted by the same tool.

**Comment by singpolyma** [comment]
I fail to see how wrapping openssl would be more dangerous than wrapping mcrypt.

I also remind people that mcrypt is *only used for cast5* -- if you use AES that is supported directly by phpseclib so this whole question only matters if you application has a specific need for cast5 (which some do, of course)

**Comment by jedisct1** [comment]
That being said, CAST5 is a very simple algorithm, which can be easily rewritten in pure PHP.

**Comment by jasekiw** [comment]
@jedisct1 is there any current implementations of this in pure PHP? We don't want to reinvent the wheel if something is already out there.

**Comment by singpolyma** [comment]
Happy to accept PRs for wrapping other methods, but I've added an OpenSSL-based CAST5 wrapper to master now -- passes tests in PHP7.1 and 7.2 without warnings now (though there are warnings if using older versions of phpseclib -- have to figure out how to tell travis which versions to use with with PHP versions...)
