### ISSUE TITLE
clearsigning

### ISSUE THREAD

**Issue by pgogy** [singpolyma/openpgp-php#6]
Hi again,
Is it possible to clear sign with this library?
I've tried a few variations (can share code) but I can't get a signature which verifies.
Thanks
Pat

**Comment by singpolyma** [comment]
There's no clearsigning helper just now, but all the machinery is there.  Should just be a matter of sticking the material you want to clearsign in a type-u data packet, signing that message, extracting the signature packet and ASCII-armoring that.  I think.

**Comment by pgogy** [comment]
Thanks, I don't get much of that (PGP is another world for me), but I get everything bar the type-u data packet and I am sure I can have a try at that 
Thanks again

**Comment by pgogy** [comment]
If I get it working I will send a sample back

**Comment by pgogy** [comment]
Hey
So here is my code, does this seem "clearsigned" to you?
It doesn't work for me (note i am using mudhairless's PSR-2 version of your code)

$options = array();
$options['format'] = "u";
$typeUPacket = new \OpenPGP\Packets\LiteralDataPacket($hashedDocument, $options);
      
$keyASCII = file_get_contents($this->getKeyPath());
$util = new \OpenPGP\Util();
$unarmor = $util->unarmor($keyASCII, 'PGP PRIVATE KEY BLOCK');
$keyEncrypted = \OpenPGP\Message::parse($unarmor);

 foreach ($keyEncrypted as $p) {
            $key = \OpenPGP\Crypt\Symmetric::decryptSecretKey($this->getPassPhrase(), $p);
            $rsa = new \OpenPGP\Crypt\RSA($key);
            $m = $rsa->sign($typeUPacket);
}
        
$util = new \OpenPGP\Util();
$headers = array(
         "Version" => "GnuPG v2"
);
$message = $util->enarmor($m->packets[0]->data[0], "PGP SIGNATURE", $headers);
$message = "-----BEGIN PGP SIGNED MESSAGE-----\nHash: SHA256\n\n" . $hashedDocument . "\n" . $message;

echo $message;

**Comment by pgogy** [comment]
If it helps it seems like there are extra lines

**Comment by pgogy** [comment]
Here are two examples
The first is via PHP, second via command line

-----BEGIN PGP SIGNED MESSAGE----- 
Hash: SHA256
 
8f3c7c6932f7e8b9f8773152212c5f65f5c07ca3

-----BEGIN PGP SIGNATURE----- 
Version: GnuPG v2

gGTHzEx8Ye5bMb5s7ih7KQN+T5Xx/cwrXgwHLsyfTBKP7zWlCFHel9avhxZM4Ojk
hXuilOTKNsebtNUesFZBwB6PxTrVw0A8sufh5rfffPELI+goyD2Hrck0umHFhUaE
MyYiHpZfplNj2hBotqHFc4FOJXQh1SOtwNibyaF3i9hejqbjPxfMgisEZqQmYGGf
TA4bJoe1mOQzj8MyHusbYFSX0wBlcpx06lCMuPxEaPxWpoqH4jKNbnroqnE3KPG2
q+c3eRRtDuUbcWyQx7Z+EML49oWpmh1NzMTrLJbCVL0+QawA0MTvW7ZsMrL9Y7u2
AQAqo4T+e1wLSyFLMeVh1A==
=SIUU

-----END PGP SIGNATURE-----

And if I use command line --clearsign

-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

8f3c7c6932f7e8b9f8773152212c5f65f5c07ca3
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQEcBAEBCAAGBQJVgYPjAAoJEO1RiXtdOTQim9MH/jhSkko67FVuT3OJ0suxzT3Z
gIDSDg6wN046C2OAqn3zcCH7htKs8bhR8NyxQ4UdeuweFT85CzyqTLt8RgiHACqw
aC4i91s9np87Pqy2qn+Ba16p+5u4QCtIxfkWzcPMnK41nakgqsgTh+yOASoCwaUm
eB7uI1wRKSVjZkskIkODK956mr4A5xLEC2/7b4z6p+KKBrayrSxtkd1M9L690VNZ
sKHvr6tHp598+i3h7yCokMoQd6+TYkoIc3KlE1Cddlf4RgKCoLwknNfdjz3c0HnB
g8f5JOQhBodZEa3LDk3BcVO/rA8npGCGMSjkHnGoysX2GLqV+nuZ8ZKu9r+S2Ao=
=SJY0
-----END PGP SIGNATURE-----

**Comment by singpolyma** [comment]
I have added a working example at https://github.com/singpolyma/openpgp-php/blob/master/examples/clearsign.php  --  I think the problem with your code is that you are not calling `to_bytes`

**Comment by pgogy** [comment]
Thanks so much for the help

I now have a merge of the two examples
require_once dirname(__FILE__).'/lib/openpgp.php';
require_once dirname(__FILE__).'/lib/openpgp_crypt_rsa.php';
require_once dirname(__FILE__).'/lib/openpgp_crypt_symmetric.php';

//filepath is just a string pointing to a password free key
$keyASCII = file_get_contents($filepath);

$keyEncrypted = OpenPGP_Message::parse(OpenPGP::unarmor($keyASCII, 'PGP PRIVATE KEY BLOCK'));

foreach($keyEncrypted as $p) {
	if(!($p instanceof OpenPGP_SecretKeyPacket)) continue;
	$key = OpenPGP_Crypt_Symmetric::decryptSecretKey($passphrase, $p);
}

/* Create a new literal data packet */
$data = new OpenPGP_LiteralDataPacket($message, array('format' => 'u', 'filename' => 'stuff.txt'));
/* Create a signer from the key */
$sign = new OpenPGP_Crypt_RSA($key);
/* The message is the signed data packet */
$m = $sign->sign($data);
/* Generate clearsigned data */
$packets = $m->signatures()[0];
echo "-----BEGIN PGP SIGNED MESSAGE-----\nHash: SHA256\n\n";
echo preg_replace("/^-/", "- -",  $packets[0]->data)."\n";
echo OpenPGP::enarmor($packets[1][0]->to_bytes(), "PGP SIGNATURE");

Doesn't produce valid sigs. I must be missing something obvious, but not sure what. I wonder if it is how the key is opened?

**Comment by pgogy** [comment]
When I do gpg --verify it says the key is not cross certified (if that helps, this is all a bit over my head)

**Comment by singpolyma** [comment]
@pgogy that sounds like a problem with the key you're signing with.

**Comment by pgogy** [comment]
Yeah, that's my conclusion. For ref
I do 
gpg --gen-key
RSA and DSA
2048
So not sure if the issue is here

**Comment by singpolyma** [comment]
Try with an RSA/RSA key maybe?

**Comment by pgogy** [comment]
Yep, a sign only key worked.
Thanks for your time, no idea what the difference was (the PSR-4 class didn't work either)
If you're on gittip or some such just let me know
Thanks a lot
Pat
