### ISSUE TITLE
sign() takes huge time

### ISSUE THREAD

**Issue by Tilogorn** [singpolyma/openpgp-php#65]
The library works as expected and returns correct results, but it takes long time to sign a small amount of (encrypted) data. PHP is version 7.0.22 running on my dev-pc-localhost.

openpgp-php was installed today by composer
```
php composer.phar info
phpseclib/phpseclib    2.0.4 
singpolyma/openpgp-php 0.3.0 
```
MWE:
```php
<?php
$start = microtime(true);

require __DIR__ . '/vendor/autoload.php';

$pubkey_fn = 'keys/public_key.asc';
$privkey_fn = 'keys/private_key.asc';

$public_key = OpenPGP_Message::parse(OpenPGP::unarmor(file_get_contents($pubkey_fn), 'PGP PUBLIC KEY BLOCK'));

$message = "openpgp-php is great!";

$data = new OpenPGP_LiteralDataPacket($message);
$encrypted = OpenPGP_Crypt_Symmetric::encrypt($public_key,new OpenPGP_Message(array($data)));

$time_elapsed_secs = microtime(true) - $start;
echo 'Encrypted at '. $time_elapsed_secs . ' Secs<br>';


$private_key = OpenPGP_Message::parse(OpenPGP::unarmor(file_get_contents($privkey_fn), 'PGP PRIVATE KEY BLOCK'));
$sign = new OpenPGP_Crypt_RSA($private_key);

$time_elapsed_secs = microtime(true) - $start;
echo 'Ready to sign at ' . $time_elapsed_secs . ' Secs<br>';

$m = $sign->sign($encrypted->to_bytes());

$time_elapsed_secs = microtime(true) - $start;
echo 'Signed at ' . $time_elapsed_secs . ' Secs<br>';

file_put_contents('gpg_encrypted_and_signed', $m->to_bytes());
?>
```

This outputs
```
Encrypted at 0.076852083206177 Secs
Ready to sign at 0.077071905136108 Secs
Signed at 17.637367963791 Secs
```
Any idea why this takes so long?

**Comment by Tilogorn** [comment]
I figured out that the reason were the amored keys. With binary keys the same script needs less than a second. Can be closed if you don't want to dig deeper (maybe a hint in the docs would be helpful).

**Comment by Tilogorn** [comment]
Forget my last post, it takes also long time with binary keys. Was a wrong assumption because of a bug in my test code.

**Comment by Tilogorn** [comment]
Could figure out that it depends on the key length. With the 1248-bit helloKey.gpg it needs less than a second, but with my 4096-bit keys it needs way longer.

**Comment by singpolyma** [comment]
Yes, because we use pure-PHP implementations of everything (for max compatibility with the shared hosting environments) big keys will be quite slow, because PHP is slow.

We could maybe try to detect common extensions that might be able to speed things up for some servers...

**Comment by singpolyma** [comment]
I think phpseclib is supposed to use mcrypt where possible to speed things up, so maybe enable that if you can?  If you do, and it's still slow, then I would open a ticket with phpseclib since they implement the primitives.
