### ISSUE TITLE
Subkey usage

### ISSUE THREAD

**Issue by veldjmaxis** [singpolyma/openpgp-php#67]
Hi,
I'm trying to use this lib for backend and openpgp.js for frontend but I can't make those two libs to work together. I think js lib needs to have subkey for encryption coz when I try to encrypt message in js using key generated by Your lib I get exception 'Could not find valid key packet for encryption in key'.
Can You help me and tell how to generate key with subkeys?

**Comment by gitBC** [comment]
see #40

**Comment by singpolyma** [comment]
@veldjmaxis If #40 doesn't help you, feel free to comment there with more context or questions.
