### ISSUE TITLE
Am not able to decrypt message

### ISSUE THREAD

**Issue by jassimcode** [singpolyma/openpgp-php#68]
Hi Guys,

Am not able to decrypt a message using the following code.
I replaced the following variables .
$keyASCII = I put my PGP key.
$msgASCII =I put my encrypted message.
and I replaced $argv[2] with my pass.

// USAGE: php examples/deASCIIdeCrypt.php secretkey.asc password message.asc
// This will fail if the algo on key or message is not 3DES or AES
require_once dirname(__FILE__).'/../lib/openpgp.php';
require_once dirname(__FILE__).'/../lib/openpgp_crypt_rsa.php';
require_once dirname(__FILE__).'/../lib/openpgp_crypt_symmetric.php';
$keyASCII = file_get_contents($argv[1]);
$msgASCII = file_get_contents($argv[3]);
$keyEncrypted = OpenPGP_Message::parse(OpenPGP::unarmor($keyASCII, 'PGP PRIVATE KEY BLOCK'));
// Try each secret key packet
foreach($keyEncrypted as $p) {
	if(!($p instanceof OpenPGP_SecretKeyPacket)) continue;
	$key = OpenPGP_Crypt_Symmetric::decryptSecretKey($argv[2], $p);
	$msg = OpenPGP_Message::parse(OpenPGP::unarmor($msgASCII, 'PGP MESSAGE'));
	$decryptor = new OpenPGP_Crypt_RSA($key);
	$decrypted = $decryptor->decrypt($msg);
	var_dump($decrypted);
}

I tried to open the message in desktop tool its open only in php it will not open it will load and fail after that timeout page will appear..

**Comment by singpolyma** [comment]
This looks the same as #66 which should be fixed in master now.  Let me know if it works for you.
