### ISSUE TITLE
Working example with saving encrypted data to file?

### ISSUE THREAD

**Issue by cxa6282** [singpolyma/openpgp-php#71]
I have the examples working, however I'm saving the encrypted file using `fopen()` and `fwrite()`. When I attempt to decrypt the file using the private key, I get errors saying the data contains certificates and can't be decrypted or verified.

Here's my encryption process:
```
$m = 'Test Text';
$pathToYourAsciiArmoredPublicKey = dirname(__FILE__).'/keys/pub.asc';
$key = \OpenPGP_Message::parse(
                                \OpenPGP::unarmor(file_get_contents($pathToYourAsciiArmoredPublicKey), 'PGP PUBLIC KEY BLOCK')
                            );
$data = new \OpenPGP_LiteralDataPacket($m);
$encrypted = \OpenPGP_Crypt_Symmetric::encrypt(
                                $key,
                                new \OpenPGP_Message(array($data))
                            );
```

I'm not sure what I should be writing to the new file... `$encrypted['0']->encrypted_data`, `$encrypted['1']->encrypted_data`, `$encrypted['2']->data` or all 3? Everything I try doesn't seem to work.

**Comment by singpolyma** [comment]
> I'm not sure what I should be writing to the new file... `$encrypted['0']->encrypted_data`, `$encrypted['1']->encrypted_data`, `$encrypted['2']->data` or all 3? Everything I try doesn't seem to work.

Probably `$encrypted->to_bytes()`

**Comment by cxa6282** [comment]
> Probably `$encrypted->to_bytes()`

That worked, thank you!
