### ISSUE TITLE
Bug decrypt

### ISSUE THREAD

**Issue by hoangnguyengia** [singpolyma/openpgp-php#72]
[8192] Function mcrypt_decrypt() is deprecated (File: vendor/singpolyma/openpgp-php/lib/openpgp_mcrypt_wrapper.php Line: [28] Trace: )

**Comment by singpolyma** [comment]
> [8192] Function mcrypt_decrypt() is deprecated (File: /tiki/www/tala/vendor/singpolyma/openpgp-php/lib/openpgp_mcrypt_wrapper.php Line: [28] Trace: )

In latest master, it will use OpenSSL if available before falling back to mcrypt. In either case, these are only used for CAST5 decryption. Also, even when deprecated the mcrypt version should still work (though it's removed in really, really new PHP)‎
