### ISSUE TITLE
Generate keys ASCII

### ISSUE THREAD

**Issue by dev3inv** [singpolyma/openpgp-php#77]
I followed the instructions in the example of [keygen](https://github.com/singpolyma/openpgp-php/blob/master/examples/keygen.php) and at the time of printing the keys (the print's shown in the example), they appear in a format of characters that do not correspond to ASCII, and I would like to know if any conversion should be done to pass it to ASCII or if those are not keys and they are obtained in another way.

Thank you.

**Comment by singpolyma** [comment]
Yes, if you want ASCII armor instead of normal OpenPGP format, then use `OpenPGP::enarmor` to convert bytes to the armor format.

For a key that would look something like:  `OpenPGP::enarmor($pubm->to_bytes(), 'PGP PUBLIC KEY BLOCK')`
