### ISSUE TITLE
Decrypt file with private key and passphrase

### ISSUE THREAD

**Issue by Daronspence** [singpolyma/openpgp-php#78]
I read through the #20 thread and am still having some issues.

I have a key file `mykey.asc` that I received from a client. They key needs a passphrase to decrypt the file `file.txt.pgp`.

When I open the `file.txt.pgp` in a text editor, I think it's in binary. I do not see any `PGP MESSAGE` headers.

Here is my code. I'm using Laravel if that matters at all.

```
$ecryptedContents = Storage::get($filename);
        $asciiKey = Storage::get($keyfilename);

        $keyEncrypted = OpenPGP_Message::parse(OpenPGP::unarmor($asciiKey, 'PGP PRIVATE KEY BLOCK'));
        
        // Try each secret key packet
        foreach($keyEncrypted as $p) {
            if(!($p instanceof OpenPGP_SecretKeyPacket)) continue;

            $key = OpenPGP_Crypt_Symmetric::decryptSecretKey('passphrase', $p);

            $msg = OpenPGP_Message::parse(OpenPGP::unarmor($ecryptedContents, 'PGP MESSAGE'));

            $decryptor = new OpenPGP_Crypt_RSA($key);
            $decrypted = $decryptor->decrypt($msg);

            var_dump($decrypted);
        }
```

The `var_dump` statement just produces NULL. When I try to change the `$msg` variable to:
 ```
$msg = OpenPGP_Message::parse($ecryptedContents);
``` 
(since there is no header), I get a fatal error saying 
`ErrorException  : Decryption error`

Totally new to all of this. I can decrypt it on the command line so that leads me to believe that it may be a configuration error.

Thanks

**Comment by singpolyma** [comment]
If `$ecryptedContents` is not in ASCII armor (no `PGP MESSAGE` headers) then you should not be calling `OpenPGP::unarmor` on it.

**Comment by vajayattila** [comment]
I tried it with 2048bits and the speed was fast.
test2048.php - Elapsed time:0.070176124572754 sec
test4096.php - Elapsed time:58.180878162384 sec

Source code:
[test 2048 and 4096 bits.zip](https://github.com/singpolyma/openpgp-php/files/3137561/test.2048.and.4096.bits.zip)

**Comment by befrednguyen** [comment]
i get the same issue. It's response NULL, any help, please

**Comment by singpolyma** [comment]
For anyone viewing this: check if both `$msg` and `$key` look reasonable -- if so, and decryption is still failing, please attach an example input file and key that you have the problem with so I can see if anything strange is happening.
