### ISSUE TITLE
Does this work with other libraries?

### ISSUE THREAD

**Issue by 1234filip** [singpolyma/openpgp-php#81]
I'm quite new to PGP but as far as I've seen it is only a standard. How could I interface this with other implemenations of PGP, for example in C++. Or is the encrypted message readable by any implementation of OpenPGP?

**Comment by singpolyma** [comment]
> I'm quite new to PGP but as far as I've seen it is only a standard. How could I interface this with other implemenations of PGP, for example in C++. Or is the encrypted message readable by any implementation of OpenPGP?

Should be readable by any complete OpenPGP implementation‎. Compatibility is regularly tested with at least GnuPG.
