### ISSUE TITLE
Need Documention About How to Armor, Encrypt (Public Key), Sign (Private key) and Compress ZIP in same time

### ISSUE THREAD

**Issue by lmlbenny** [singpolyma/openpgp-php#90]
can i get some clue to do this in OPENPGP.

gpg --armor -output sample_output.asc cipher ases256 --compress-algo ZIP -s2k-digest-algo SHA256 --encrypt --recipent gogo@go.com --sign - u<<private key>> to_be_signed.text

**Comment by singpolyma** [comment]
https://github.com/singpolyma/openpgp-php/blob/master/examples/armorEncryptSignCompress.php
