### ISSUE TITLE
Expiration check on PGP key

### ISSUE THREAD

**Issue by grcasanova** [singpolyma/openpgp-php#95]
I noticed when parsing a PGP key there is a property named _v3_days_of_validity_, how can it be used to determine the key validity and is it compatible with most generation algorithms?

**Comment by singpolyma** [comment]
`v3_days_of_validity` is only for v3 keys, of which there are very few in the wild.  In general what you will actually want is to look for a `OpenPGP_SignaturePacket_KeyExpirationTimePacket` inside a self-signature on the key.
